package routers

//Auto generated code for hiring workers.
//DO NOT EDIT THIS FILE.
import worker "github.com/herb-go/worker"

func init() {
	//Worker "routers.ActionAuthfail"
	//You can add Introduction by add comment in form WORKER(ActionAuthfail):Introduction
	worker.Hire("routers.ActionAuthfail", &ActionAuthfail)

	//Worker "routers.RouterAPIFactory"
	//You can add Introduction by add comment in form WORKER(RouterAPIFactory):Introduction
	worker.Hire("routers.RouterAPIFactory", &RouterAPIFactory)

	//Worker "routers.RouterFactory"
	//You can add Introduction by add comment in form WORKER(RouterFactory):Introduction
	worker.Hire("routers.RouterFactory", &RouterFactory)

}