#Presethttpinfo config file
[[Extractors]]
Name="appidheader"
Type="header"
[Extractors.Config]
Field="appid"

[[Extractors]]
Name="secretheader"
Type="header"
[Extractors.Config]
Field="secret"

[[Extractors]]
Name="timestampquery"
Type="query"
[Extractors.Config]
Field="timestamp"

[[Extractors]]
Name="signquery"
Type="query"
[Extractors.Config]
Field="sign"

[[Extractors]]
Name="appidquery"
Type="query"
[Extractors.Config]
Field="appid"

[[Extractors]]
Name="path"
Type="path"

[[Extractors]]
Name="filename"
Type="filename"

[[Extractors]]
Name="basicuser"
Type="user"

[[Extractors]]
Name="basicpassword"
Type="password"


[[Fields]]
Name="appidheader"
Extractor="appidheader"

[[Fields]]
Name="secretheader"
Extractor="secretheader"

[[Fields]]
Name="timestampquery"
Extractor="timestampquery"

[[Fields]]
Name="signquery"
Extractor="signquery"

[[Fields]]
Name="appidquery"
Extractor="appidquery"

[[Fields]]
Name="path"
Extractor="path"

[[Fields]]
Name="filename"
Extractor="filename"

[[Fields]]
Name="basicuser"
Extractor="basicuser"

[[Fields]]
Name="basicpassword"
Extractor="basicpassword"