package middlewares

//Auto generated code for hiring workers.
//DO NOT EDIT THIS FILE.
import worker "github.com/herb-go/worker"

func init() {
	//Worker "middlewares.MiddlewareCsrfSetToken"
	//You can add Introduction by add comment in form WORKER(MiddlewareCsrfSetToken):Introduction
	worker.Hire("middlewares.MiddlewareCsrfSetToken", &MiddlewareCsrfSetToken)

	//Worker "middlewares.MiddlewareCsrfVerifyForm"
	//You can add Introduction by add comment in form WORKER(MiddlewareCsrfVerifyForm):Introduction
	worker.Hire("middlewares.MiddlewareCsrfVerifyForm", &MiddlewareCsrfVerifyForm)

	//Worker "middlewares.MiddlewareCsrfVerifyHeader"
	//You can add Introduction by add comment in form WORKER(MiddlewareCsrfVerifyHeader):Introduction
	worker.Hire("middlewares.MiddlewareCsrfVerifyHeader", &MiddlewareCsrfVerifyHeader)

}